name: Hello World

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World !"
      - run: echo "added multiple steps"
      - run: echo "using 4 jobs"
  job2:
    runs-on: ubuntu-24.04
    steps:
      - run: print("hello world from python")
        shell: python
  job3:
    runs-on: ubuntu-24.04
    needs:
      - job1
      - job2
    steps:
      - run: echo "hello in job3"
  job4:
    runs-on: ubuntu-24.04
    needs:
      - jobs2
      - jobs3
    steps:
      - run: echo "final job"
